version: '3.8'

services:
    back:
      container_name: noteSecure-back
      build:
          context: back/
          dockerfile: Dockerfile.dev
      volumes:
      - ./back/:/usr/src/app/
      - /usr/src/app/node_modules/
      ports:
      - 8000:8000
      environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      stdin_open: true

    front:
      container_name: noteSecure-front
      build:
          context: front/
          dockerfile: Dockerfile.dev
      volumes:
      - ./front/:/usr/src/app/
      - /usr/src/app/node_modules/
      ports:
      - 3000:3000
      environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      stdin_open: true
      
networks: 
    back_network:
        driver: bridge
